### ISSUE TITLE
INFO

### ISSUE THREAD

**Issue by daltonjames777** [Karim-Arab/Bulk-Tiktoks-Downloader#18]
You fix the code, thank you, you are the best and I appreciate your work, I had two questions if you could answer I would appreciate it a lot, you made the code to download videos from snaptik, can the code be changed to download from tikmate - for example or from somewhere else, and the second question, can the videos be downloaded, with a higher resolution, snptik has offered the download in HD but I don't know why it has been removed as an option.
I wish you the best, and I appreciate you for the work you do!

**Comment by Karim-Arab** [comment]
yea it adjustable just change selectors and might even less steps than snaptik , you can also make it more quicker if changed math function but it might be detect by cloudflare or tiktok azure, i guess HD option not available anymore since Tiktok protect their API from automated bots , i just do trying to make simple as much as possible
